### ISSUE TITLE
As a Beacon manager I want to put the new version of the API and web app in production

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/beacon-suedtirol-administration-android#31]
**TODOS**
- [x] Bring the new API version and web app online (the concluded development of Davide Montesin et al.)
- [x] Approve the new Android Admin App on the play store which was rejected before + release it on the Alpha channel
> Redeployed, no credentials were asked by Google. Let's see what happens with version 2.3.0?
- [x] Test: Native app: what happens if someone that can not modify certain beacons, modifies them via the native app (should not crash, but just say not allowed) 
> App does not crash, if the logged in user has not the rights to modify data a "Authorization expired. Please log in again!" popup is shown
> Issues can be saved. That should be ok
- [x] Write to @ohnewein about a possible contract with Davide Montesin to integrate groups and permission handling into the Android Admin App
> @sseppi said, we need first to talk with other stakeholders and then decide how to proceed
- [x] Create a separate user story for the testing native android admin app deployment, which can be postponed due to the Corona crisis and the non-usage of the production app, which we used for testing at the moment
> See #32 
- [x] Fix an issue where all beacons show a "no signal" status
> Nothing to fix, see #33 for details (it is just a bad wording of a status, which should just say, not seen for some time, status unknown)
- [x] Release the app (v0.3.0) to production
> Done, but waiting for release. Google says: "We're currently reviewing your app. This is normally done within 7 days, but can occasionally take longer." (So, in the worst case it will be 20/05/2020; @sseppi FYI)

----
Result of our conf call from 2020-04-03:
- APP for Beacon ADMIN to test the new API
- Native app: what happens if someone that can not modify certain beacons,
  modifies them via the native app (should not crash, but just say not allowed)
- Investigate how we can integrate the new changes to the native app about group
  permissions etc.
- davide montesin should fix it and/or add new functionalities (if possible, we need to ask Patrick O first)
- apk for testing, not alpha channel, just download and manually install for internal testers
- look analytics to see if the current production app is used and could be used for testing
